import { Injectable } from '@angular/core';
import { serialize } from '@thi.ng/hiccup';
import { OptionalFilter, StyleService } from './style.service';

interface ErlMineralOccurrenceStyleParams {
  optionalFilters?: OptionalFilter[];
  color?: string;
  gsmlNamespace?: string;
  gmlNamespace?: string;
  erlNamespace?: string;
}

@Injectable()
export class ErlMineralOccurrenceStyleService {
  /**
   * Generate SLD for ERL Mineral Occurrence layers
   * @param layerName The name of the layer
   * @param styleName The style name
   * @param params Parameters including optionalFilters
   * @returns SLD XML as a string
   */
  public static getSld(layerName: string, styleName: string, params: ErlMineralOccurrenceStyleParams): string {

    const styleParams = {
        erlNamespace:
          params?.erlNamespace ||'http://xmlns.earthresourceml.org/earthresourceml-lite/2.0'
      };

    const ns = {
      sld: 'http://www.opengis.net/sld',
      ogc: 'http://www.opengis.net/ogc',
      gml: 'http://www.opengis.net/gml',
      gsml: 'urn:cgi:xmlns:CGI:GeoSciML:2.0',
      erl: styleParams.erlNamespace, //'http://xmlns.earthresourceml.org/earthresourceml-lite/2.0', // Use ERL 1.0 to match backend
      xlink: 'http://www.w3.org/1999/xlink',
      ows: 'http://www.opengis.net/ows',
      xsi: 'http://www.w3.org/2001/XMLSchema-instance'
    };

    const color = params.color || '#e02e16';
    const filter = StyleService.generateFilter(params.optionalFilters || []);

    const sld = serialize(
      ['sld:StyledLayerDescriptor', {
        version: '1.0.0',
        'xmlns:sld': ns.sld,
        'xmlns:ogc': ns.ogc,
        'xmlns:gml': ns.gml,
        'xmlns:gsml': ns.gsml,
        'xmlns:erl': ns.erl,
        'xmlns:xlink': ns.xlink,
        'xmlns:ows': ns.ows,
        'xmlns:xsi': ns.xsi,
        'xsi:schemaLocation': [
          `${ns.sld} http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd`,
          `${ns.erl} http://schemas.earthresourceml.org/earthresourceml-lite/1.0/earthresourceml-lite.xsd`
        ].join(' ')
      },
        ['sld:NamedLayer', {},
          ['sld:Name', {}, layerName],
          ['sld:UserStyle', {},
            ['sld:Name', {}, styleName],
            ['sld:Title', {}, 'ERL Mineral Occurrence Style'],
            ['sld:Abstract', {}, 'Mineral Occurrence style generated by AuScope Portal'],
            ['sld:FeatureTypeStyle', {},
              ['sld:Rule', {},
                ['sld:Name', {}, 'ERL Mineral Occurrence View'],
                ['sld:Title', {}, 'ERL Mineral Occurrence View'],
                ['sld:Abstract', {}, 'Circle'],
                filter,
                StyleService.createSymbolizer(color,'circle', '1')
              ]
            ]
          ]
        ]
      ]
    );
    return sld;
  }
}
