import { Injectable } from '@angular/core';
import { serialize } from '@thi.ng/hiccup';
import { OptionalFilter, StyleService } from './style.service';

interface ErlCommodityStyleParams {
  optionalFilters?: OptionalFilter[];
  color?: string;
  gsmlNamespace?: string;
  gmlNamespace?: string;
  erlNamespace?: string;
}

@Injectable()
export class ErlCommodityStyleService {
  /**
   * Generate SLD for ERL Commodity Resource layers
   * @param layerName The name of the layer
   * @param styleName The style name
   * @param params Parameters including optionalFilters
   * @returns SLD XML as a string
   */
  public static getSld(layerName: string, styleName: string, params: ErlCommodityStyleParams): string {
    const ns = {
      sld: 'http://www.opengis.net/sld',
      ogc: 'http://www.opengis.net/ogc',
      gml: 'http://www.opengis.net/gml',
      gsml: 'urn:cgi:xmlns:CGI:GeoSciML:2.0',
      erl: 'http://xmlns.earthresourceml.org/earthresourceml-lite/1.0',
      xlink: 'http://www.w3.org/1999/xlink',
      ows: 'http://www.opengis.net/ows',
      xsi: 'http://www.w3.org/2001/XMLSchema-instance'
    };

    const color = params.color || '#940ea3';
    const filter = StyleService.generateFilter(params.optionalFilters || []);

    const sld = serialize(
      ['StyledLayerDescriptor', {
        version: '1.0.0',
        'xmlns': ns.sld,
        'xmlns:sld': ns.sld,
        'xmlns:erl': ns.erl,
        'xmlns:gml': ns.gml,
        'xmlns:ogc': ns.ogc,
        'xmlns:xlink': ns.xlink,
        'xmlns:ows': ns.ows,
        'xmlns:xsi': ns.xsi,
        'xsi:schemaLocation': 'http://www.opengis.net/sld StyledLayerDescriptor.xsd'
      },
        ['NamedLayer', {},
          ['Name', {}, layerName],
          ['UserStyle', {},
            ['Title', {}, 'ERL Commodity Resource Style'],
            ['Abstract', {}, 'Commodity Resource style generated by AuScope Portal'],
            ['FeatureTypeStyle', {},
              ['Rule', {},
                ['Name', {}, 'ERL Commodity Resource View'],
                ['Title', {}, 'ERL Commodity Resource View'],
                ['Abstract', {}, 'Circle'],
                filter,
                StyleService.createSymbolizer(color, 'circle', '1')
              ]
            ]
          ]
        ]
      ]
    );
    return sld;
  }
}
