import { Injectable } from '@angular/core';
import { StyleService } from './style.service';
import { serialize } from '@thi.ng/hiccup';

interface MinOccurViewStyleParams {
  commodityName?: string;
  minOreAmount?: string;
  minReserves?: string;
  minResources?: string;
  bbox?: string;
  maxFeatures?: number;
}

@Injectable()
export class MinOccurViewStyleService {
  constructor(private styleService: StyleService) {}

  public static getSld(layerName: string, styleName: string, params: MinOccurViewStyleParams): string {
    const ns = {
      sld: 'http://www.opengis.net/sld',
      ogc: 'http://www.opengis.net/ogc',
      gml: 'http://www.opengis.net/gml',
      mo: 'http://xmlns.geoscience.gov.au/minoccml/1.0',
      xlink: 'http://www.w3.org/1999/xlink',
      xsi: 'http://www.w3.org/2001/XMLSchema-instance'
    };


    return serialize(
      ['sld:StyledLayerDescriptor', { 
        version: '1.0.0',
        'xmlns:sld': ns.sld,
        'xmlns:ogc': ns.ogc,
        'xmlns:gml': ns.gml,
        'xmlns:mo': ns.mo,
        'xmlns:xlink': ns.xlink,
        'xmlns:xsi': ns.xsi,
        'xsi:schemaLocation': `${ns.sld} StyledLayerDescriptor.xsd`
      },
        ['sld:NamedLayer', {},
          ['sld:Name', {}, layerName],
          ['sld:UserStyle', {},
            ['sld:Name', {}, styleName],
            ['sld:Title', {}, styleName],
            ['sld:Abstract', {}, 'MinOccurView style generated by AuScope Portal'],
            ['sld:IsDefault', {}, '1'],
            ['sld:FeatureTypeStyle', {},
              ['sld:Rule', {},
                this.createSymbolizer()
              ]
            ]
          ]
        ]
      ]
    );
  }

  private static createSymbolizer(): any[] {
    return [
      'sld:PointSymbolizer', {},
      ['sld:Graphic', {},
        ['sld:Mark', {},
          ['sld:WellKnownName', {}, 'circle'],
          ['sld:Fill', {},
            ['sld:CssParameter', { name: 'fill' }, '#ed9c38'],
            ['sld:CssParameter', { name: 'fill-opacity' }, '0.4']
          ],
          ['sld:Stroke', {},
            ['sld:CssParameter', { name: 'stroke' }, '#ed9c38'],
            ['sld:CssParameter', { name: 'stroke-width' }, '1']
          ]
        ],
        ['sld:Size', {}, '8']
      ]
    ];
  }
} 