import { Injectable } from '@angular/core';
import { StyleService } from './style.service';
import { serialize } from '@thi.ng/hiccup';

interface MineralOccurrenceStyleParams {
  commodityName?: string;
  measureType?: string;
  minOreAmount?: string;
  minOreAmountUOM?: string;
  minCommodityAmount?: string;
  minCommodityAmountUOM?: string;
  optionalFilters?: OptionalFilter[];
}

interface OptionalFilter {
  value: string;
  label: string;
  xpath: string;
  predicate: string;
  type: string;
  added: boolean;
}

@Injectable()
export class MineralOccurrenceStyleService {
  constructor(private styleService: StyleService) {}

  public static getSld(layerName: string, styleName: string, params: MineralOccurrenceStyleParams): string {
    const ns = {
      sld: 'http://www.opengis.net/sld',
      ogc: 'http://www.opengis.net/ogc',
      gml: 'http://www.opengis.net/gml',
      gsml: 'urn:cgi:xmlns:CGI:GeoSciML:2.0',
      er: 'urn:cgi:xmlns:GGIC:EarthResource:1.1',
      xlink: 'http://www.w3.org/1999/xlink',
      xsi: 'http://www.w3.org/2001/XMLSchema-instance'
    };

    // Create filter fragments
    const fragments = [];

    // Add commodity filter if provided
    if (params.commodityName) {
      fragments.push(['ogc:PropertyIsEqualTo', {},
        ['ogc:PropertyName', {}, 'gsml:specification/er:MineralOccurrence/er:commodityDescription/er:Commodity/er:commodityName'],
        ['ogc:Literal', {}, params.commodityName]
      ]);
    }

    // Process optional filters
    if (params.optionalFilters) {
      params.optionalFilters.forEach(filter => {
        switch (filter.type) {
          case 'OPTIONAL.POLYGONBBOX':
            fragments.push(['ogc:Intersects', {},
              ['ogc:PropertyName', {}, 'gsml:shape'],
              ['gml:Polygon', {}, filter.value]
            ]);
            break;
          case 'OPTIONAL.TEXT':
            fragments.push(['ogc:PropertyIsLike', { wildCard: '*', singleChar: '#', escapeChar: '!' },
              ['ogc:PropertyName', {}, filter.xpath],
              ['ogc:Literal', {}, `*${filter.value}*`]
            ]);
            break;
        }
      });
    }

    // Create filter
    const filter = fragments.length > 0 ? 
      ['ogc:Filter', {},
        fragments.length > 1 
          ? ['ogc:And', {}, ...fragments]
          : fragments[0]
      ] : null;

    return serialize(
      ['sld:StyledLayerDescriptor', {
        version: '1.0.0',
        ...this.generateNamespaces(ns)
      },
        ['sld:NamedLayer', {},
          ['sld:Name', {}, layerName],
          ['sld:UserStyle', {},
            ['sld:Name', {}, styleName],
            ['sld:Title', {}, styleName],
            ['sld:Abstract', {}, 'Mineral Occurrence style generated by AuScope Portal'],
            ['sld:IsDefault', {}, '1'],
            ['sld:FeatureTypeStyle', {},
              ['sld:Rule', {},
                filter,
                this.createSymbolizer('#8C489F')
              ]
            ]
          ]
        ]
      ]
    );
  }

  private static generateNamespaces(ns: any): object {
    return Object.entries(ns).reduce((acc, [key, value]) => ({
      ...acc,
      [`xmlns:${key}`]: value
    }), {});
  }

  private static createSymbolizer(color: string): any[] {
    return [
      'sld:PointSymbolizer', {},
      ['sld:Graphic', {},
        ['sld:Mark', {},
          ['sld:WellKnownName', {}, 'circle'],
          ['sld:Fill', {},
            ['sld:CssParameter', { name: 'fill' }, color],
            ['sld:CssParameter', { name: 'fill-opacity' }, '0.4']
          ],
          ['sld:Stroke', {},
            ['sld:CssParameter', { name: 'stroke' }, color],
            ['sld:CssParameter', { name: 'stroke-width' }, '1']
          ]
        ],
        ['sld:Size', {}, '8']
      ]
    ];
  }
} 