import { Injectable } from '@angular/core';
import { StyleService } from './style.service';
import { serialize } from '@thi.ng/hiccup';

interface MiningActivityStyleParams {
  mineName?: string;
  startDate?: string;
  endDate?: string;
  oreProcessed?: string;
  producedMaterial?: string;
  cutOffGrade?: string;
  production?: string;
  bbox?: string;
}

@Injectable()
export class MiningActivityStyleService {
  public static getSld(layerName: string, styleName: string, params: MiningActivityStyleParams): string {
    const ns = {
      sld: 'http://www.opengis.net/sld',
      ogc: 'http://www.opengis.net/ogc',
      gml: 'http://www.opengis.net/gml',
      er: 'urn:cgi:xmlns:GGIC:EarthResource:1.1',
      gsml: 'urn:cgi:xmlns:CGI:GeoSciML:2.0',
      xlink: 'http://www.w3.org/1999/xlink',
      xsi: 'http://www.w3.org/2001/XMLSchema-instance'
    };

    return serialize(
      ['sld:StyledLayerDescriptor', {
        version: '1.0.0',
        ...this.generateNamespaces(ns)
      },
        ['sld:NamedLayer', {},
          ['sld:Name', {}, layerName],
          ['sld:UserStyle', {},
            ['sld:Name', {}, styleName],
            ['sld:Title', {}, styleName],
            ['sld:Abstract', {}, 'Mining Activity style generated by AuScope Portal'],
            ['sld:IsDefault', {}, '1'],
            ['sld:FeatureTypeStyle', {},
              ['sld:Rule', {},
                StyleService.createSymbolizer('#FF9900', 'circle', '1')
              ]
            ]
          ]
        ]
      ]
    );
  }

  private static generateNamespaces(ns: any): object {
    return Object.entries(ns).reduce((acc, [key, value]) => ({
      ...acc,
      [`xmlns:${key}`]: value
    }), {});
  }
}
