name: Azure Static Web Apps Production CI/CD

on:
  push:
    branches:
      # this will be prod so set filters here to control when a release is pushed to the prod static web app
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      # and here
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: jsdaniell/create-json@v1.2.2
        with:
          name: "context.json"
          json: '{"portalBaseUrl":"${{ vars.AZURE_PORTAL_URL_PROD }}/api/","hostUrl":"${{ vars.AZURE_PORTAL_URL_PROD }}"}'
          dir: 'src/contexts/'
      - name: Update proxy.json file
        uses: jossef/action-set-json-field@v2.1
        with:
          file: proxy.conf.json
          field: target
          value: "${{ vars.AZURE_PORTAL_URL_PROD }}/api/"
      - name: print proxy.conf.json
        run: cat proxy.conf.json
      - name: Set redirect for geonetwork in staticwebapp.config.json
        uses: jossef/action-set-json-field@v2.1
        with:
          file: staticwebapp.config.json
          field: "routes[0].redirect"
          value: "${{ vars.GEONETWORK_URL_PROD }}"
      - name: print staticwebapp.config.json
        run: cat staticwebapp.config.json
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_FLOWER_08081A31E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_FLOWER_08081A31E }}
          action: "close"
